apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productcatalog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/aws-containers/eks-app-mesh-polyglot-demo
    path: /workshop/helm-chart
    targetRevision: HEAD
  destination: 
    name: eks-demo
    namespace: default