apiVersion: backstack.cncf.io/v1alpha1
kind: EKSCluster
metadata:
  name: backstack-eks
  namespace: default
spec:
  parameters:
    id: backstack-eks
    region: us-west-2
    iam:
      roleArn: arn:aws:iam::845587322796:instance-profile/eks-workshop-admin
    version: "1.28"
    nodes:
      count: 3
      instanceType: t3.small
  writeConnectionSecretToRef:
    name: backstack-eks-kubeconfig
  publishConnectionDetailsTo:
    name: backstack-eks/backstack-eks-kubeconfig
    configRef:
      name: vault